---
- name: Create ~/.emacs.d
  file:
    path: ~/.emacs.d
    state: directory
- name: install emacs config
  copy:
    dest: ~/.emacs.d/init.el
    src: files/emacs/init.el
- include: emacs.{{ansible_distribution}}.yaml
