---
- name: install emacs on MacOS
  homebrew:
    name: emacs
    state: latest
  notify: restart emacs daemon {{ansible_distribution}}

- name: Install emacs plist
  copy:
    dest: ~/Library/LaunchAgents/org.shtsh.emacs.plist
    src: files/emacs/org.shtsh.emacs.plist
  notify: restart emacs daemon {{ansible_distribution}}

- name: Run emacs daemon
  shell: launchctl list | grep org.shtsh.emacs || launchctl load ~/Library/LaunchAgents/org.shtsh.emacs.plist
  register: launchctl_emacs
  changed_when: launchctl_emacs.stderr == ""
