---
- name: Install and configure important software
  ansible.builtin.include_tasks:
    file: "{{ item }}.yaml"
  with_items:
    - "brew"
    - "neovim"
    - "tmux"
    - "fish"
    - "wezterm"
  tags:
    - always

# Install formula foo with 'brew' in default path
- name: Install packages via brew
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ developer_homebrew_packages }}"
  tags:
    - packages
    - brew

# Installs pacakges from appstore
- name: Install packages via appstore
  community.general.mas:
    id: "{{ item.id }}"
    state: present
  with_items: "{{ developer_mas_installed_apps }}"
  tags:
    - packages
    - appstore

- name: Install config directories
  ansible.builtin.copy:
    src: "files/{{ item.name }}"
    dest: "{{ item.dst }}"
    mode: preserve
  with_items:
    - { name: "starship.toml", dst: "~/.config/" }
  tags:
    - configs
