---
- name: Checkout repo
  ansible.builtin.git:
    repo: 'git@github.com:Shtsh/ansible-macos-env.git'
    dest: ~/Hobby/pyenv-rs
    update: no
  tags:
    - rsvenv

- name: Check rsvenv is installed
  ansible.builtin.shell:
    cmd: which rsvenv
  register: rsvenv_installed
  ignore_errors: true
  changed_when: false
  tags:
    - rsvenv

- name: Install rsvenv
  ansible.builtin.shell:
    chdir: ~/Hobby/pyenv-rs/
    cmd: cargo install --path . --root ~/.cargo/
  when: rsvenv_installed is failed
  tags:
    - rsvenv
