---
- include: zsh.{{ansible_distribution}}.yaml
- name: install zsh config files
  copy:
    dest: "{{ zsh_config.dest | default(zsh_config) }}"
    src: "files/zsh/{{ zsh_config.src | default(zsh_config) }}"
  with_items: "{{ zsh_files }}"
  loop_control:
    loop_var: zsh_config
- name: install zsh theme
  git:
    repo: "{{ zsh_theme.repo }}"
    dest: "{{ zsh_theme.dest }}"
- name: install more zsh config files
  copy:
    dest: "{{ zsh_config.dest | default(zsh_config) }}"
    src: "files/zsh/{{ zsh_config.src | default(zsh_config) }}"
  with_items: "{{ zsh_files_postinstall }}"
  loop_control:
    loop_var: zsh_config
  

  
