---
- hosts: localhost
  connection: local
  
  vars_files:
    - config.yaml

  roles:
    - role: developer
      tags: ['developer']
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      tags: ['mas']

