import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "Transparent"
startup_mode = "Fullscreen"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 15

[scrolling]
history = 100000

[env]
TERM = "xterm-256color"
